# Generated by Django 4.2.7 on 2025-12-18 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0001_initial'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='transaction',
            name='tracker_tra_user_id_ea3525_idx',
        ),
        migrations.AlterField(
            model_name='financialreport',
            name='data',
            field=models.JSONField(default=dict),
        ),
    ]
